### PR TITLE
Add Mint Reward Exchange Example

### PR DESCRIPTION
**Pull request by DerekSiemens**
## Description of the change

Adding reward exchange example so that it can be picked and plopped into widgets and microsites

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: https://saasquatch.atlassian.net/browse/DEV-3363
- Process.st launch checklist: https://app.process.st/runs/DEV-3363-Reward-Exchange-Frontend-tcLRvS-d_y7AYZSInb9ONA

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

### CODE REVIEW

**Comment by DerekSiemens** [comment]
@00salmon why is the jest test build failing?

**Comment by 00salmon** [comment]
> @00salmon why is the jest test build failing?

seems to be a workflow / memory issue maybe? i've gotten a few different errors after rebuilding a few times (that said, i can't even run this locally and getting an entirely different error i don't know how to fix 😓)

i think we should just remove this test from the workflow, it seems to be trying to run it using puppeteer, which i don't think it used to do.

**Comment by DerekSiemens** [comment]
@00salmon okay, unfortunate but sounds good for now - what tests is it running tho?

**Review by 00salmon — APPROVED** [review]
this should be good to go now 👍

**Pull request merged**
